apiVersion: apps/v1
kind: Deployment
metadata:
  name: ach-api
  namespace: heracles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ach-api
  template:
    metadata:
      labels:
        app: ach-api
    spec:
      containers:
        - name: ach-api
          image: localhost:5000/heracles/ach-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: heracles-config
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ach-api
  namespace: heracles
spec:
  type: LoadBalancer
  selector:
    app: ach-api
  ports:
    - port: 8082
      targetPort: 8080


