apiVersion: v1
kind: ConfigMap
metadata:
  name: heracles-config
  namespace: heracles
data:
  TEMPORAL__ADDRESS: "host.docker.internal:7233"
  TEMPORAL__NAMESPACE: "default"
  ConnectionStrings__Payments: "Data Source=/data/payments.db"
  ConnectionStrings__Ach: "Data Source=/data/ach.db"
  ConnectionStrings__Sftp: "Data Source=/data/sftp.db"
  ASPNETCORE_URLS: "http://+:8080"
